-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 08, 2020 at 04:26 PM
-- Server version: 10.4.6-MariaDB
-- PHP Version: 7.3.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `slum`
--

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` int(6) UNSIGNED NOT NULL,
  `author` int(6) UNSIGNED NOT NULL,
  `title` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `body` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `post_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `author`, `title`, `body`, `post_date`) VALUES
(19, 441, 'Maze', 'Looking down on this place \r\nFinding way in this maze\r\nDont know \r\nWhat is real? \r\n\r\nI am living in this dream\r\nI forget i have self asteem\r\nLost on this way \r\nfor my soul\r\n\r\n', '2019-02-17 15:38:26'),
(30, 444, 'Vábnička', 'Za starých časů už mechanismus vyráběný,\r\nz dřevěné patičky a kusu drátku,\r\ndo temné díry lstivě nastražený\r\nlapá po myším pařátku.\r\nTohle je ale pastička, ne vábnička.\r\n\r\nSpějeme do rozuzlení.\r\n\r\nVábnička je v našem případě sýr.\r\nAni camembert, ani gouda, ani skyr,\r\nAle úplně obyčejný a hnusný eidam.\r\nVlk se nažere a koza zůstane celá.\r\nPřítomnost eidemu v domácnosti rozzuří požitkáře do běla.\r\nAle myš ne, myš je ráda.\r\nDo té doby, než jí prasknou záda.\r\n', '2019-02-18 07:34:22'),
(31, 444, 'Básník', 'Životabudiči! Kurviči!\r\nPijí a pak se zbijí do němoty.\r\nNevidíš rozdíl mezi nimi a chudáky na šroty.\r\nMouka je jako louka do které se v poledne unaven svezeš,\r\nživotodárný kvásek jsou včelky.\r\nBídné žebračí ruce se pnoucně vztahují,\r\nSukně povětrničky se vzdouvají.\r\nPo vlhkých kočičích hlavách klepou podpatky barda.\r\nNa loutnu rád tklivě hrává,\r\nskrz noční okno do místnůstky chce vlézt,\r\na sevřít dívčí ňadra. \r\n\r\nJeho básně sice rvou srdce, lítostí se celý chvěješ,\r\nchceš znovu držet v dlaních tu bytost pro tebe nejkrásnější.\r\nSám se ale básník příliš bojí.\r\nNechce ženu, která kojí,\r\nchce se stát nadzemskou nesmrtelnou entitou.\r\nChce splynout s někým dalším,\r\nChce docílit nejvyššího souznění duší.\r\nNedostane ale do zad znovu kuší?\r\n\r\nRadši by si odřezal uši a schnil.\r\n', '2019-02-18 07:38:35'),
(32, 444, 'Asi láska', 'Hedvábné deky ukrývají dvě rozechvělá těla,\r\nbronzové zjizvené ruce hladí záda oděná do běla.\r\nJen chvíle uběhla od toho, kdy vzdechy protínaly vzduch,\r\ntichý patron lásky se vplížil, oba mají ale napnutý sluch.\r\nPod jemným splynutím bělostné tělo v kříži se prohýbalo,\r\nsnědé stvoření se rozkoší z polibků zajíkalo.\r\n\r\nNevyřčená slova bolí, zastírají mozek.\r\nV zpoceném opojení se do nich vešel celý svět.\r\nNěmě se mezi doteky sebe ptali, „Je to láska?“\r\nTěla chtějí navždy stejný tón pět,\r\nsrdce touží bít vedle sebe,\r\nrozum tomu ale zoufale brání,\r\nnejsme svoji, i když tě teď hladím po skráni.\r\n\r\nHorkost těl přímo ovlivňuje hořkost skutečnosti.\r\n\r\nČlověk se chce oddat malomocnosti,\r\nbrání mu v další rozkoši,\r\nuvolní mu ale mysl.\r\nTohle rozptýlení má smysl.\r\nMá smysl se kát za nezodpovědný útěk od světa,\r\npříště se mu vetřeš do přízně,\r\npříště jseš ty osvěta.\r\nJemné doteky kalí myšlenky,\r\nchci se jen procházet v trávě v rosénky.\r\nTkát si šaty ze slz je nevyhnutelné, průhledné nitky chladí,\r\nleda že se zbavíš té přítěže,\r\nco ti teď čeří myšlenky a hraje si s tvými vlasy.\r\n\r\nUž nechceš víc, pořád stejná písnička,\r\nStále chceš víc, příště to bude jiné.\r\nSpolečně dobýváte se a kdo ví jak to skončí?\r\nProvaz se dá použít hravě, nebo taky lynčí.\r\n', '2019-02-18 07:40:36'),
(33, 441, 'Staroměstská', 'Obloha s tisícemi ptáků \r\nMi pluje nad hlavou \r\nKolem mě procházejícíc\r\nNespočet draků\r\nKteří vydechují duši \r\nA já s nimi... ', '2019-02-18 19:20:46'),
(34, 441, 'Zlato', 'Slabost, slabost pro tebe mě tíží \r\nNevim jak to mám říci,\r\n v hlavě mi to víří\r\nJe to něco jiného a dost to bolí. \r\nCo si mám myslet a co mám všem povědět.\r\nŽe asi láskou jsem zahořel... \r\nShořel spíše a má mysl tyhle řádky píše. \r\nPopálený, až na kost od všech smyslů. \r\nPropálený bolestí. \r\nCo mám dělat, co měnit. \r\nMysl utvrdit.', '2019-02-18 19:25:28'),
(35, 441, 'Všechno', 'Neni mi fajn. \r\nA co já stim? \r\nVracím se tam \r\nKde jsem byl. \r\nZtrácím se tu\r\nA nevím jak dál \r\nKdo mi ty hezký pocity \r\nAsi vzal...', '2019-02-18 21:16:23'),
(36, 441, 'Změna je život', 'Mám se snažit \r\nMám to vzdát? \r\nVsechno ztratit \r\nDál se prát? \r\nZlepšit věci \r\nZlepšit sebe \r\nZmenit všechno \r\nVzdat se tebe? \r\nZmenit vůli na svět \r\nZmenit proc dal bojovat \r\nZmenit proc dal žít \r\nA nebo to dal spojovat..? \r\n', '2019-02-18 21:26:00'),
(37, 444, 'Humbert Humbert', 'Am I wondering with my eyes?\r\n\r\nAm I wandering with my fingers?\r\n\r\nOver your sleepy body\r\n\r\nAm I just watching you or do you feel my heat?\r\n\r\nWhat is reality \r\n\r\nYou\'re so sweet\r\n\r\nMy eyes are watering because baby\r\n\r\nTears are canned cries for help\r\n\r\nAre those tears mine or yours?\r\n\r\nMine are clear and your are bloody\r\n\r\nWhat have I done\r\n \r\nI should\'t have touched your body', '2019-02-18 23:36:27'),
(38, 444, 'Večery', 'Žiji jenom ve vzpomínkách,\r\nsociální konstrukt existence,\r\ntak zapáleně jako doutnající zbytek svíčky.\r\nProvazy mi svazují okolo zápěstí smyčky.\r\nVypudí ze mě ducha po čas seance,\r\nNavrátí ho k žití v běžných výjimkách.  \r\n', '2019-02-19 20:10:39'),
(39, 444, 'Dívky aneb Osobový freestyle ', 'Hani, půjdeš s náma?\r\nBereme tě jako kamaráda.\r\nMyšlenka se k myšlence sejde,\r\nty tomu nerozumíš ani co se za nehet vejde.\r\n\r\nMáme tě rádi jako člověka, Hani.\r\nStejně se ale na mě sápete.\r\n\r\nKoukněte na ni.\r\nV ručce smutně drží zmačkanou sukni,\r\npanenku zpět do ruky ji vnukni.\r\n\r\nNebude si s námi hrát.\r\n', '2019-02-19 20:11:29'),
(40, 444, 'Heterosexuální vztah', 'Měkká stehna jsou pohodlnější,\r\nnež tvrdá dlažba myšlenek.\r\n', '2019-02-19 20:12:00'),
(41, 450, 'Sonet určený k zapomenutí', 'Na zemi prašné, kam padla hlava sťatá\r\nKde rudý plevel, prach potřísněný krví\r\nTam smysl ztrácí pravda, láska svatá\r\nProč rány smutku čas tak snadno hojí\r\n\r\nKdyž říkáte si: “Navždy budem svoji”\r\nVyřčění slibů je o význam připraví\r\nPak ztrácíte se v nekonečném boji\r\nZeď vzteku rozum snadno otupí\r\n\r\nPřed božím soudem, i krutý vrah by změk\r\nSlova jsou tvar, jen následkem jsou hlasu\r\nŽal náš a neskonalý vztek\r\nJsou jen jak kameny v řece času\r\n\r\nMáme vše a stejně chceme víc\r\nŽivot jak šat, co má jen rub a líc', '2019-02-21 01:27:12'),
(42, 450, 'Pouliční prodavač', 'Přišel ke mně znenadání\r\nzastihl mne v uličce temné\r\na po zdvořilém uvítaní\r\nnabídl mi špetku skořice jemné\r\n\r\nHladká zrnka zrezivělá\r\nsypou se mu mezi prsty\r\nmá povaha již k tomu spěla\r\nže nepohrdnu, jsem si jistý\r\n\r\nVzal jsem od něj rovnou deka\r\nnení třeba skromný být\r\nskořice je moje Mekka\r\n a v ní klidně hodlám hnít\r\n\r\nSkořici jím, skořici dýchám\r\nSkořice naději mi dala\r\nŽivot se skořicí mýchám\r\nSkořice mi ho vzala\r\n\r\nPravdu ve skořici hledám\r\nObčas sním že dnes si nedám', '2019-03-29 23:04:24'),
(43, 450, 'Epitaf', 'Na pohřeb ti přijde víc lidí než na narozeniny.\n       -Andrej', '2019-02-24 22:05:15'),
(53, 452, 'A Socialist', 'It’s that time of the year,\r\nWhere we bash some poor Communists,\r\nWe start with basic economics and beer,\r\nEnd up discussing a masochist.\r\n\r\nHowever, once a faint blue moon,\r\nA genetical alteration appears,\r\nIt’s called a Socialist loon,\r\nA living abnormality that brings tears,\r\n\r\nTorn between a communist and a Democrat,\r\nNo ordinary insults work against this demon,\r\n“Go have a hunger strike in a gulag,”\r\nWorks like paper money in Sweden.\r\n\r\nAnd even though it seems I hate them,\r\nI\'ll just go back to chewing gum.\r\n', '2019-02-26 16:39:32'),
(54, 452, 'Back in \'nam', 'A drugged up black dude is playing the anthem,\r\nA granny is eating apple pie in Harlem,\r\nA white boy is about to get his mind open,\r\nand I\'m here fucking an Asian whore with no lotion.\r\n\r\nHow did we get to this damn point,\r\nWe were heroes, now villains behind the gunpoint,\r\nWhy are we fighting against freedom?\r\nWhere the hell is the goddamn reason?\r\n\r\nWill this put our proud nation to trouble?\r\nReducing cultures and villages to mere rubble?\r\nWill they ever forgive us?\r\nWill we ever forgive ourself?\r\n\r\nBut I think there is a bloody thrill,\r\nI\'m the fortunate son that was born to kill. ', '2019-02-26 16:55:32'),
(89, 441, 'Zloděj ', 'Cestou a polem\r\nPostavám s kolem\r\nA přemýšlím,\r\nco vlastně bude dál \r\n\r\nMíjel jsem cesty a města\r\nAt je jim všem zem lehká \r\nZa chvíli už tu ani my nebudem.\r\n\r\nChybí ty lidičky \r\nA krásný hračičky\r\nO které jsem přišel, \r\nzlodějem časem. \r\n\r\nSnad nepřijdu o duši \r\nO které netuším. \r\nAle je pro mě nejdůležitější \r\n\r\nSnad mi ji nevezme\r\nŘíkám ji Zůstaňme\r\nAle ona už se chystá na cestu kratkou\r\n \r\nKonec, \r\nvše utichlo\r\nNic už tu není \r\nA už jen čekám, \r\naž ten zloděj\r\nVše zhojí.', '2019-02-27 07:02:01'),
(105, 457, 'Fellák', 'Mám jednoho felláka\r\nJmenuje se Vít \r\nVyhul mu ptáka \r\nJestli chceš Vašek pass mít \r\n\r\nMám jednoho felláka \r\nŘíkám mu Šperle \r\nTy si tak křivej \r\nŽe by si měl nosit berle ', '2019-03-01 14:47:45'),
(106, 457, 'Dějepis ', 'Steinerova vstupuje \r\nA začíná dějepis \r\nTakhle dobře neuspí tě\r\nAni prášky na předpis \r\n\r\nPřivrený oči \r\nUspaváč hadů \r\nPrvní cena v soutěži \r\nZnuděnejch výkladů \r\n\r\nByzantska říše \r\nHlava padá k lavici \r\nMyslí si že jsme \r\nJenom pofiderni tragici ', '2019-03-01 14:49:34'),
(108, 441, 'Cit', 'Zřím světlo kolem sebe\r\nblíží se \r\nA barví se nebe\r\nRůžově, zlatě, modře\r\nA celá ta krása \r\njen mě sleduje\r\nJako bych byl někdo důležitý! \r\n\r\nJá jsem jen ztracený\r\nVe svých nehezkých básních \r\nA jediná vášeň\r\nCo dokážu v sobě projevit\r\nJsou myšlenky na tebe\r\n\r\nCo mě rozežírají ze vnitř \r\nA ničí to všechno \r\nA uhasínají ten... \r\nTen zbytečný plamínek\r\nKterý zde přebývá... ', '2019-03-13 11:42:29'),
(109, 441, 'Zvuk', 'Klep, klep\r\nKlepání zoufalství \r\nHrajeme mi v uších \r\nA přidává smutku\r\nDalší emoci\r\nStrach \r\nPo kterým mi ochlazuje tělo \r\nNepříjemný pot\r\nKterý jako jizva \r\nMi říká \r\nCo jsem to provedl! \r\n', '2019-03-13 11:44:10'),
(110, 441, 'Svázaná', 'Světlo ozařuje\r\ntvé měkké rty \r\nA já jen čekám\r\naž je budu moct zas ucítít\r\n\r\nSvazujeme se\r\nJak jehlou a nití\r\nSnad už se od sebe \r\nnebudeme muset nikdy oddělit. \r\n\r\nI když tohle říkám\r\nvím co zloděj udělá\r\nSebere mi\r\nty tvoje odlišné myšlenky\r\nA předá je někomu krásnějšímu\r\nLepšímu\r\n\r\nA já tu zbudu zde, \r\njen jako tvor, \r\nco ti na chvíli\r\nomámil hlavu a\r\nnic \r\nvíc. ', '2019-03-13 11:50:35'),
(111, 441, 'Sám', 'Ztrápený hlavou a srdcem \r\na z očí crčí strach \r\na zlost \r\n\r\nVybral jsem si tě \r\nNepouštěj mě ven\r\nProč to nejsme my dva jen? \r\n\r\nUbírá mi kousek po kousku\r\njako kus měsíce \r\nna tmavé obloze\r\n\r\nTu temnotu\r\nvšak doplňují svítivé hvězdy\r\nZa ty to stojí\r\n\r\nA proto stále  \r\nJá a ty \r\nA já se jen snažím věřit\r\nŽe nikdo jiný... \r\n', '2019-03-31 19:38:25'),
(112, 457, 'Vyjetý koleje ', 'Ovce konzumujou\r\nSami padaj do pasti\r\nPřeskládám jim koleje\r\nDo nekončící propasti\r\n\r\nChovám se jak to cítím \r\nJe to někdy těžký \r\nJít cestou pravdy \r\nObčas znamená jít pěšky ', '2019-03-14 19:02:51'),
(113, 444, 'Dušno', '     Okno do duše    Šepot v uších\r\n     Duše v okně       Hoši v duši\r\n     Okno v duši        Šípy v srdci\r\n     Okno v okně       Ruce v okně\r\n     Duše v duši         Duše v koši', '2019-03-27 10:31:32'),
(116, 444, 'Náklonnost', 'Rozloučení beze slov\r\nšum vln omílá břehy\r\nBezbřehé zahradě,\r\nrůže již uvadly.', '2019-03-27 10:39:32'),
(117, 444, 'Den a noc', 'Potřebuješ paprskovité Slunce,\r\nprohřát své ztuhlé údy,\r\nchvíli nevšimneš si \r\nže zalévá tě modrá záře\r\nAle potom se i od ní odvrátíš.', '2019-03-27 10:41:13'),
(149, 462, 'člověk nad tureckou kávou', 'V kapce kávy Afriku zhlédnout\r\nv jedné mantiji ruky Bosánky\r\nPřes tajné příběhy nepřehlédnout\r\no rty otřít si banánky\r\nsladce penězmi koupené\r\nv hlavě nápady uloupené\r\n\r\nMezi čtverečky prostěradla skrývá se klíč Arché,\r\nvzpomenout si jak jsou kosmické dimenze plaché\r\ndo dalekých končin vesmíru\r\nkoukat se nekonečně\r\nvěčně a v každém fenoménu\r\nhledat část lidského doménu\r\nbez šance.\r\nJedno kolo ve vozu je pouhým kolem ve vozu.', '2019-03-27 19:56:28'),
(150, 462, 'před poděkováním', 'zatáhnul jsem rolety před dvěma nedělema\r\nfík i banán v mém pokoji už zvadly\r\nfotka tebe pokrytá mrtvýma buňkama\r\nusmívá se i když to nevidím\r\n\r\nsvěží vánek kymácí náhrdelníkama na okenní klice\r\nmeruzalky, šacholány, třešně\r\nodpoledne krášlí Modřanovy silice\r\n\r\nta svěžest přinesla mi nejen opět jí\r\nale i pot na mých dlaních\r\na lepí se mi vlasy, dnes mi zpívá Yves Montand\r\nneviděl bych ven a neviděl bych nic\r\nkdybych ty rolety neroztáh\'\r\ntvoje a sluneční paprsky\r\nmi vyrovnali páteř a kytkám žít daly dál.', '2019-03-31 19:36:10'),
(151, 441, 'Jizvy', 'Každý měsíc \r\nKaždé hvězdy \r\nČekám \r\nAž se ztratí\r\n\r\nUteče mně \r\nProbodne mě \r\nVezme mi všechen cit\r\nA všechnu naději \r\nKteré ve mně už moc nezbývá \r\n\r\nNeztrácej dech má milá \r\nJseš můj důvod\r\nProč se chovám \r\nJako já. ', '2019-03-31 19:34:09'),
(152, 450, 'Když potkáš zázrak', 'Když potkáš zázrak\r\n\r\nBuď sám oběť\r\n\r\nDobrý den\r\n\r\nVšem lidem\r\n\r\nCo mám rád\r\n\r\n     -Apoštol Arnošt', '2019-03-31 19:32:15'),
(153, 460, '30. března', 'Kdyby ve mně bylo trochu lidskosti,\r\nsevřela bych v prstech kousek křídy, \r\naž by mi zbělely klouby\r\na šla psát na schody pod Stalinem\r\npísmena tak veliká,\r\nže by je přečetli tažní ptáci\r\nvracející se z jihu.\r\n\r\n&quot;Vítejte doma, milovaní&quot; \r\ndokola a dokola.\r\naž by na schodech nezůstal\r\nani kousek volného místa.', '2019-03-31 20:08:35'),
(154, 461, 'Nature\'s call', '[read in a Scottish accent]\r\n\r\nHear me younglings short and tall\r\nDon\'t ignore the nature\'s call\r\nSometimes I hear her in my mind\r\nBlaming me with all our kind\r\n\r\nYour human kind has gone too far\r\nYou left here more than just one scar\r\nWoods are burned and lakes are dried\r\nI heard them scream, for long they cried\r\n\r\nI ignored her, now I regret\r\nDrowned in shame, my pants are wet.', '2019-04-08 18:05:20'),
(155, 452, 'Read fast m8', 'I am not a pheasant plucker, \r\nI\'m a pheasant plucker\'s son.\r\nI am only plucking pheasants \'till the pheasant plucker comes.\r\n\r\n- bless this bloke', '2019-04-09 17:10:33'),
(156, 452, 'Rub-A-Dub (Cockney Rhymes)', 'Well rub a dub dub\r\nCatch me at a pub,\r\nAnd call me Jack Sprat,\r\nWatchin’ telly crap.\r\n\r\nBrexit, tad blental,\r\nOhhh Brexit, like the country went radio rental,\r\nCan’t tickle a fancy, \r\nWithout gettin’ inna prancy.\r\n\r\nTold my missus I’ll grab a quick one,\r\nShe’s the jam tart, my cow and kisses,\r\nBollocks, there comes my manhole cover,\r\n\r\nHe found himself a Pall Mall,\r\nNow they are having a Gawd Fawbid,\r\nBloody hell the brandy butter,\r\nWhat a crown and anchor.\r\n\r\nShe’s soon to be a mother pride,\r\nMy old pot and pan is having a blast,\r\nSkin and Blisters is in flisters,\r\nShe can be a real ruck and row,\r\n\r\nI ask him, “OI wat’s your pick and choose,”\r\nHe says “I’ll start with Britney Spears”\r\n“Maybe some Mother’s Ruin or Vera Lynn,\r\nLet\'s add a Finger thumb, \r\nthen couple bright and frisky,\r\nadd a couple Currant cakes,\r\nend it at a Plikety plonk,\r\nAnd I’ll be right as rain.”\r\n\r\n“This’ll be only Dynamite,\r\nBarney Rubble and Bull and cow,”\r\nHe looks dead in the eye\r\n“And Remember, no fags,”\r\n\r\n\r\nA glossary to understand what the fuck did you just read\r\nRub-A-Dub – pub\r\nJack Sprat - brat \r\nRadio rental – mental\r\nCan’t tickle a fancy – fight a Doris Day(gay)\r\nJam tart – sweetheart\r\nCow and kisses – missus\r\nManhole cover – brother (Sweet)\r\nPall Mall – gal\r\nGawd Forbid – Kid\r\nBrandy Butter – nutter\r\nCrown and anchor - wanker\r\nmother pride – bride\r\nOld pot and pan – (my) old man\r\nSkin and Blisters – sister\r\nruck and row – cow\r\npick and choose – booze\r\nBritney Spears – beer \r\nMother’s Ruin / Vera Lynn – Gin\r\nFinger thumb – rum\r\nBright and frisky – whisky\r\nCurrant cakes – the shakes\r\nPlikety plonk - wine\r\nDynamite – fight \r\nBarney Rubble – Trouble\r\nBull and cow – row \r\nFag(s) – cigarettes\r\n\r\nIf you still don’t understand it, well then tough shit bitch.\r\n', '2019-04-09 17:57:50'),
(157, 441, 'Hřeje', 'Doušek a francouzský hlas \r\nHřeje v těle \r\nA na duši \r\nA krása lidského setkání \r\nZe mně vyvádí \r\nŠtěstí \r\nA chybí mi už jen pár \r\nMaličkostí \r\n\r\nA někdy ty maličkosti \r\nDokážou být \r\nNejvětší a nejdražší \r\nNa celým světě \r\n\r\nVelká část chybí \r\nAle zaplňuju jí\r\nZeleným čajem a hřejevým\r\nSetkáním \r\n', '2019-04-13 16:16:31'),
(158, 441, 'King Heroin', 'Ladies and gentlemen\r\nFellow Americans\r\nLady Americans\r\nThis is James Brown\r\nI wanna talk to you about one of our\r\nMost deadly, killers in the country today\r\nI had a dream the other night, and I\r\nWas sittin\' in my living room\r\nDozed off to sleep\r\nSo I start to dreamin\'\r\nI dreamed I walked in a place and\r\nI saw a real strange, weird object\r\nStandin\' up talkin\' to the people\r\nAnd I found out it was heroin\r\nThat deadly drug that go in your veins\r\nHe says\r\nI came to this country without a passport\r\nEver since then I\'ve been hunted and sought\r\nMy little white grains are nothin\' but waste\r\nSoft and deadly and bitter to taste\r\n\r\n- James Brown ', '2019-04-13 20:40:55'),
(159, 450, 'Balada o tuze švarném hochu a zlatovlásce', 'Potkali se na bále a zahořela láska\r\nOn byl tuze švarný hoch a ona zlatovláska\r\nHle jejich vztah snad určil osud\r\nAlespoň se zdálo dokud\r\nOna nenašla si jinou\r\nSnad nebylo to její vinou\r\n \r\nOn jí to však nevyčítal, nevyměnil by ji za nic\r\nByť by bylo dobré zmínit, že byl stále ještě panic\r\nPřesto v hloubi duše věděl, že jeho láska nezná hranic\r\n \r\nI když jí v cestě stojí celý svět\r\nHrdě se rozhodl, že ji získá zpět\r\n \r\nZvolil cestu věru krušnou\r\nZa odměnou tuze tučnou\r\nOblékl na sebe šat hodný šlechtice\r\nA svižně odkráčel do její vesnice\r\n \r\nKdyž vyznal jí lásku svou, a teď snad naposled\r\nZačala litovat a nešetřila slov\r\nMilenku svojí odnesla na hřbitov\r\nA jejich příběh začíná znova, i když uprostřed\r\n \r\n\r\nJejich nový vztah však trpký nádech měl\r\nI když to měla být štěstěna nová\r\nZůstalo nakonec jen u styku dvou těl\r\nA nechtěli si říkat jen zdvořilá slova\r\n \r\nJak to už bývá a čtenář již vytuší\r\nŽe začala litovat, že zkusila to znova\r\nTento vztah jí nenechal jizvy jen na duši\r\nTak jednoho dne odešla směrem do venkova\r\n \r\nHoch se pak v posteli vzbudil už bez ní\r\nStarost ho sužovala a rozhodl se konat\r\nA tak vydal se za ní po cestě mezní\r\nBůh tomu snad chtěl, že náhle začal stonat\r\n \r\nKdyž se blíží k vesnici, nohy ho už sotva nesou\r\nNáhle klesá na kolena a upadá do mdlob\r\nOpouští ho život a ruce se mu třesou\r\nKdyž na kraji hřbitova spatří vykopaný hrob\r\n', '2019-04-14 13:34:43'),
(160, 444, 'Óda o cigaretách', 'Kouřím, protože jsem skaut.\r\n\r\nVůně troudu pohladí mi chřýpí,\r\na já si rázem vzpomenu jak v ohni pálíme lípy.\r\n\r\nDatuji to do přísnovlády bratra Přemka.\r\nOheň zapálený lupou hoří lépe nežli petrolejka.\r\n\r\nOranžová světélka pro mě znamenají dobrodružství.\r\n\r\nMyšlenky křtěné ohněm jsou hlubší nežli jiné.\r\nSvětélkují jak světlušky, tak my v letním kině.', '2019-04-16 13:16:23'),
(161, 466, 'nechci', 'máš tisíc očí a jen jedna ústa \r\na ty nemluví \r\n\r\n.\r\n\r\nmoje duše je mělká \r\nfénixi\r\nnemůžu za to\r\nbído\r\n\r\n.\r\n\r\ndaleko\r\nale ne až zas tak moc \r\n\r\n.\r\n\r\nživot  na čtyři doby \r\npřestal sem tě hledat \r\npojď ke mně blíž\r\nnechci\r\n\r\n.\r\n\r\nsamota\r\nprázdnota \r\nžalota\r\nza plotem holota\r\nz lidí co znám\r\nznám jejich postele \r\nznám jejich duše \r\na oni nechtějí znát tu mou\r\nuž ji poznali?\r\n\r\n.\r\n\r\nnechci tě nechci tě nechci tě\r\ntrnová koruna svírá ti hrdlo \r\ntrny z mý růže\r\naspoň že jsem měla trochu tvý kůže\r\n\r\n.\r\n\r\njdeme vedle sebe já se bojím\r\ntebe ty se bojíš mně \r\ntvoje ústa říkají řeči vně \r\npodstata podstata podstata \r\nvýluka myšlenek\r\npojďme něco zplodit \r\naspoň \r\nbojím se sebe a ty se bojíš tebe \r\nnechci tě\r\nkdyž mně ty už nechceš \r\nhorká kaše hořký kafe \r\n\r\n.\r\n\r\nmušle a perly \r\nperly žen a mušle mužů\r\nemoce a volby\r\nemoce žen a volby mužů\r\n\r\n..............................................................\r\n\r\nvíce či méně volný asociace od www neurobeat', '2019-04-21 22:26:16'),
(162, 467, 'Hejkal', 'Na zápraží stařec sedí\r\nOdbila již desátá\r\nDo temnoty tiše hledí\r\nVedle něho vnoučata\r\n \r\nCigareta mdle mu plane\r\nŠero občas prozáří\r\nDěvče malé náhle vstane\r\nZlostný úsměv na tváři\r\n \r\nJak se děvče kvapem zvedne\r\nVrásčitá tvář rychle bledne\r\nSám má strach z nočního lesa\r\nZná hejkala, zlého běsa\r\n \r\nZastav, běda, křičí děda,\r\nAle holka nevyčká\r\nNa starcovy rady nedá\r\nZkouší svého dědečka\r\n \r\nPak ztratí se v husté tmě\r\nDuch lesa se usměje\r\nNež tu se ozve křik\r\nNejdřív dívky a pak ryk\r\n \r\nRozléhal se lesem, řev\r\nSnad jako sta čertů zpěv\r\nA dědek hledal marně\r\n \r\nKonečně našel ji ráno\r\nNa pařezu dřepící\r\nZkrvavenou na líci\r\nOhluchlou a blouznící', '2019-04-29 21:23:11'),
(163, 468, 'Seminárka', 'Pozdě, ale přeci zkouším,\r\njak tento produkt od Jakuba \r\nbude se tvářit na mé verše, \r\npři jejichž psaní se vznáším.\r\n', '2019-05-14 13:48:05'),
(164, 467, 'Galantní hoch', 'Po ulici hrdě kráčí chlapec\r\nNa kolemjdoucí s radostí se usměje\r\nKšandy, pásek, zapnutý poklopec\r\nGalantním hochem Jonatán je\r\n\r\nKudrlinky ve větru mu vlají\r\nOn pečuje si o své kadeře\r\nDěvčata se za ním ohlížejí\r\nJeho však nebaví jejich hašteře\r\n\r\nOn totiž, jako správný džentlmen\r\nNemešká okamžiku, kdy vyšel ven\r\nRazí si cestu do galantérie\r\nJak šelma, co vydala se do prérie\r\n\r\nNakoupit si: nitě, látky, jehly,\r\nTo jest, v čem on je nejvíc zběhlý', '2019-05-16 14:24:41'),
(165, 469, 'Uchopit sen', 'Letím nad dlažbou, obklopen zborcenými přežitky kamenných budov.\r\nPohled upřený před sebe, za mnou leží jen most přes řeku s výhledem na vzdálené centrum města, jehož světla trhají podvečerní oblohu.\r\nLetím bezcílně ale jasně vím kam.\r\nZa zatáčkou mě přitažlivost opět přijme.\r\nZůstává jen bahnitá cesta a nekonečný svah nízkých kamenných zídek, linie je očividná.\r\nUž jsme tři a cesta ubíhá rychleji, když v ní nemusíme hledat opodstatnění.\r\nSpatřili jsme ji jakmile padla mlha, viněta tunelu se úží\r\nNa čtyřech v blátě její ostré zuby odrážely světla našich baterek, jako oči jelena chyceného v mlhovkách auta.\r\nS každou vteřinou jejího upřeného pohledu se cesta začíná bortit, ale neschopnost pokračovat není beznadějná, naopak dává cíli smysl.\r\nOna nevstává. Bláto už jí prosáklo až k obličeji vyzdobeném zuby jako schizofrenická noční obloha, formující rozohněný úsměv agresivního chtíče potřeného vrstvou krve.\r\nNež nám stihl její pohled vypálit do duše pentagram, odtáhli ji za vodítko přidělané k její kožené svěrací kazajce a cesta pokračovala.\r\nPo měsíční krajině jsme došli až k náměstí. Pod nohama kočičí hlavy a kolem nás agorafobické množství ničeho. Cíl se stále přibližoval.\r\nNaše vědomí počechrala tlumená hudba a nespočet neonových ornamentů, dohromady tvořících jakousi opoužívanou koláž nočního života.\r\nProšli jsme mřížemi a kouřovou clonou a chvíli po vzpamatování už nás uchvátila extatická vášeň.\r\nZa dveřmi institutu nás očekával jen nespočet pomalovaných chodeb, ve kterých procházeli oni, pohrouženi do svých nových očí, které jim trčely jako uhlíkové monolity z obou očí, a ve středu formovaly postupně gradující věž, na jejímž vrcholku zářil jeden jediný zelený bod.\r\nOči upřené na ruce a pohrouženi do studií, procházeli chodbami proti nám, zatímco my už jsme byli téměř na kraji propasti.\r\nChodba končí, a vznáším se temnotou. Moji společníci už nejspíš konec našli. Nekonečnost pádu mu bere směr. Hudba ke mě stále doléhá a pulzuje mi celým tělem jako elektrický náboj.\r\n\r\nKonec je stále prázdnější než začátek, zbývá poslední slovo: Sofie\r\n', '2019-05-26 22:39:23'),
(166, 452, 'Hong Kong', 'Ching Chong\r\nBing Bong\r\nI play Ping Pong\r\n\'cause my shlong is long', '2019-06-04 20:39:04'),
(167, 461, 'Identita', 'Já, to jsi ty?\r\nNe.\r\nTo jsem já.', '2019-06-04 22:19:10'),
(168, 470, 'washing machine', 'Oh, suck a dick,\r\n(or I suck yours?)\r\nOne last time I\'ll do the dishes\r\n(when night comes \'round I\'ll be on my fours\r\n\r\n-granting all your wishes)\r\n \r\nIn the kitchen I dream about my secret slutty life\r\n(But don\'t you worry- I am still your sweet little fifties\' wife)\r\n\r\n\r\n', '2019-06-22 19:20:15'),
(169, 470, 'dear Morfeus,', '1110000 1101100 1100101 1100001 1110011 1100101 100000 1100111 1100101 1110100 100000 1101101 1100101 100000 1101111 1110101 1110100 100000 1101111 1100110 100000 1101000 1100101 1110010 1100101 ', '2019-06-22 19:26:19'),
(170, 471, 'podvodník?', 'Studené výrazy,\r\nzkoumavé pohledy,\r\nsvětýlka Casina vrhají odrazy.\r\n \r\nTěžký vzduch, asi z doutníků,\r\ntahle noc bude plna neznámých poutníků.\r\n\r\nPříjdou a přisednou, nedaj\' si obědnat,\r\nolíznou rty a začnou prostě hrát.\r\nNemá je nikdo rád,\r\npak se jen čeká, než budou švindlovat.\r\n\r\nVětšinou poklidný,\r\npot z čela mu nestéká,\r\nnekouká se po kočkách,\r\nočima je nesvléká.\r\n\r\nJak plyne noc a blíží se ráno,\r\nmizí i pocit, že máte vyhráno.\r\n\r\nNeznámý potník pobafá a dumá,\r\nna kulatém stolku obrovská suma.\r\n \r\nNedočkaví protivníci mají oči na stopkách,\r\nčekají až dohrají ti, které jistě čeká krach.\r\n \r\nNáhle v ten okamžik poutník je na tahu-\r\nhraje.\r\n\r\nDech taje.\r\n\r\nÚčastníci turnaje,\r\nnehledě na výdaje, \r\n\r\nsázeli na to že prohraje.\r\n\r\nPoutník sklízí, co jiný seje,\r\nteď peníze maje,\r\nví, že vyhraje.\r\n\r\nBere peníze, tu celou sumu,\r\ns úsměvem na tváři utíká zas \'domů\'.\r\nProtihráče na pokraji krachu\r\nnechává v prachu.\r\n\r\nCasino se za ním sesouvá k zemi, \r\nPoutník se na cestu zas vydává.\r\nSláva!\r\nTakhle se vyhrává!\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n', '2019-06-26 21:29:44'),
(171, 472, 'Moře', 'Přemíra slov a pocitů\r\nPrázdná sklenice a strach\r\nZ dostupnosti mých citů\r\nVšechno se mění na prach\r\n\r\nOtevírám štěstí brány\r\nKlesám dolů do moře\r\nSlaná voda hojí rány\r\nKdyž se člověk pořeže\r\n\r\nMám držet se pevně?\r\nMáme držet se za ruce?\r\nKdo vidí to stejně?\r\nNehledej ty emoce\r\n\r\nPřístav už je blízko\r\nParkování drahé\r\nV dálce kamení se blýsklo\r\nŠaty mé drahé\r\n\r\nBrzy přijde šero\r\nVšechno uzavře se v nás\r\nBeru do rukou pero\r\nVšechno vykoupí jen čas\r\n\r\nPřijímám svůj osud\r\nNedržím se pevniny\r\nNic nebude jak dosud\r\nAž získám pocit viny\r\n\r\nVolám už jen k sobě\r\nPomoc už nechci, nehledám\r\nVidím tě v jiné době\r\nVšechno co bylo, vrátí se nám\r\n\r\nSebe dávám v sázku\r\nNedokážu dát to ven\r\nVšechnu tu lásku\r\nKterá mění se na sen', '2019-07-19 21:27:47'),
(172, 473, 'Ssssscosi', 'Říká se nedráždi hada bosou nohou,\r\nale kolem mě jsou všichni bosí.\r\nKamarádi říkají že rádi davají, \r\nale radši berou,\r\na já potom co jsem viděl,\r\nse každej večer svlíkám z kůže,\r\nco ty roky nosím.\r\nTak prosím, kdo si. \r\nŽe můžeš říkat o hadovi, co se skrývá v houští,\r\nže je zlosyn.\r\nŽe hadí princ je míň, když místo toho,\r\naby si kopal s míčem, kopl do hnízda,\r\nkde jsou vosy.\r\nŽe je život špatně prožitej,\r\nkdyž tě najdou v jedný ruce s básničkou\r\na v druhý se stříkačkou \r\nnebo s kulkou v hlavě,\r\njako Sida a Nancy.\r\nJak víš co je plus a co je minus,\r\nkdyž měsíc je doopravdy nejblíž\r\nv odrazu rosy.\r\nCo jsi, a tvoje názory, o tom,\r\nco je realita, život a klam,\r\ndokuď si nepoznal smrt kosy.\r\nA mě princovi, svítí zatím hadí oči\r\nod krve, když se plavím s Cháronem\r\npřes řeku Styx nekoněčnou nocí.\r\nKaždej na smrtelným lůžku prosí\r\nnebo mlčí\r\nnebo jako dítě v tom koloběhu řve a brečí,\r\nsnad ho nikdo neuslyší, je pozdě,\r\nnastal čas a už pod jeho nohy had syčí.\r\nSssscosi.', '2019-07-23 10:04:54'),
(173, 457, 'Sny', 'Nejradši mám když\r\nNení sluneční svit\r\nVšichni lidi spěj\r\nProto je takovej klid\r\n\r\nTakovej klid\r\nkolem sebe nic neslyšíš\r\nVenku je tma\r\nKrása když nic nevidíš \r\n\r\nAle když spím \r\nTak miluju ten stav \r\nSny jsou vážně krásný \r\nKina uprostřed hlav', '2019-08-03 09:15:49'),
(174, 474, 'Moje závislost', 'Nevím, jeslti toho bylo moc, \r\nnerozeznal jsem den a noc. \r\nAsi to bylo tenkrát z nudy\r\nnebo jsem neovládl svoje pudy. \r\n\r\nNevím, kde mi hlava stojí \r\nani co se děje v mysli mojí. \r\nCitím se vlastně skvěle, \r\ntolik síly najednou v mém těle. \r\n\r\nNevím, jestli mi je hrozně nebo krásně, \r\nale o tom stavu mohl bych psát básně. \r\nChci si dát zase, ale o dost víc, \r\na pak budu křičet z plných plic. \r\n\r\nNevím, s kým to bylo poprvé, \r\nkdyž jsem to dostal do krve\r\nMoje paměť čelí výpadku, \r\nměl bych si dát přestávku. \r\n\r\nNevím, jeslti přežiju další dávku, \r\nmoje tělo vyhlašuje stávku. \r\nNevěděl jsem co dávám v sázku, \r\nkdyž jsem poprvé do sebe vpravil lásku... \r\n', '2019-08-22 22:16:18'),
(175, 475, 'Těm dívkám', 'Tuto báseň všem těm dívkám věnuju\r\nkdyž stával jsem v parku a v dešti\r\na kladl si otázku kde seš ty\r\nproč sám tak sám zámkům panuju\r\n\r\nVšem těm dívkám na které nepřestanu myslet\r\nty noci, všechny ty noci mi na mysl přicházejí\r\na mé srdce jako stará almara prázdnotou zejí\r\nděkuji vám že mohl jsem hladit vaší ruky hřbet\r\n\r\nVšem těm dívkám které ronily pro mne své slzy\r\nomlouvám se vám, každé, za své činy\r\nprosím pohlaďte večer po vlasech naše syny\r\nna věky už budu obdivovat vaše pózy\r\n\r\nVšem těm dívkám co jsou pryč\r\nnezapomenu na vás nadosmrti\r\ni když vím že byste byly proti\r\nproč jen jsem nenašel v postelých váš klíč ', '2019-08-27 20:17:26'),
(176, 475, 'Nebezpečí krásného snu', 'Prozpěvoval jsem si svoje sny\r\ntobě se mezitím krátily moje dny\r\nsmutně jsi tam smutná ve smutku stála\r\nkdyž si mě smrt bezohledně brala\r\n\r\nStála jsi s dlaní hlíny\r\nzatímco mě mlely boží mlýny\r\nlidi k tobě přicházeli a odcházeli\r\nmy jsme naše dny zbytečně prosázeli\r\n\r\nAni smrt hrdinská ani věkem důstojná\r\nnad hrobem stojíš deštěm zmáčená\r\ncítíš se nekonečně ztracená\r\nnení to tak dlouho co stála jsi přede mnou svlečená\r\n\r\nByl jsem jenom poutník na ohřání\r\nkterému se s tebou vyplnila všechna přání\r\nBudu na tebe čekat za oponou mlhy\r\nvejdeme pak spolu mezi bohy', '2019-08-27 20:24:01'),
(177, 475, '12.7, 12.8', 'Stačil mi jen jeden večer\r\nabych propadl tvým očím\r\nu řeky jsem v tu chvíli klečel\r\nkdyž došlo mi že u lásky skončím\r\n\r\nStačila mi jen sklenka vína\r\nabych propadl tvým zlatým vlasům\r\nnespadlo mi jablko do klína\r\nmusím tě ukrást všem těm hezkým chlapcům\r\n\r\nStačilo mi jen jedno sousto z jídla\r\nabych podlehl tvým tvarům\r\nnestačilo nám na naše těla mýdla\r\nabychom učinili přítrž starým zmarům\r\n\r\nStačilo mi jen zaslechnout tvůj hlas\r\nabych úplně podlehl tvým slovům\r\ndoufám jen že na mně se bažíš stejných krás\r\nabychom spolu mohli patřit k šťastným tvorům', '2019-08-27 20:39:57'),
(178, 444, 'Dvě těla jedna duše', 'Pozlátko ulic,\r\nšedých jako sedlina z výroby mýdla,\r\nmilenecká láska držíc se za ruce.\r\n\r\nUkaž lásce líc, neboj se nic.\r\nLáska přichází a odchází se šustem kyvadla.\r\n\r\nDvě těla jedna duše blíží se k luce.\r\nCelé odpoledne střídají stráně, seno, mech.\r\nZe rtů jde kromě &quot;miluju tě&quot; něžný vzdech.\r\n\r\nDvě těla jedna duše unavila se. \r\nJehlice borovic jako osten hořkosti do milenců zaklesl se.\r\n&quot;Nechci a nemiluju tě&quot;\r\n\r\nSilné pouto důvěry rozdělilo se opět v dva.\r\nLáska opadla dříve, než opadla tma.\r\n\r\nDvě těla jedna duše, už ani nevzpomene si\r\nna dlouhé chvíle,\r\nzírání do očí, oken do duše.\r\n\r\nSpolečná duše zemřela.', '2019-09-05 19:44:52'),
(179, 444, 'Binární soustava', 'Sopka emocí a vlasy zplihlé potem,\r\nstrávila jsem s tebou celý den.\r\n\r\nSlunce bedlivě pozorovalo všechen náš smích,\r\nbylo ho požehnaně,\r\nVypiji radši klíh,\r\nvše lepší než srdce rozervané.\r\n\r\nCítím se pokojně, když si prohlížím mraky,\r\ntmavozelený trávník hladí mé rozpálené tváře.\r\nZ tátových škodovek zbyly jen vraky,\r\nvykresluji si červené obrazce do tkáně.\r\n\r\nProkletí jin a jang, pocity mi jsou čínským písmem,\r\ndojemné vzpomínky mé duše pelest,\r\nnemohu tě obdarovat šťastné duše věnem,\r\n\r\nžití za trest.\r\n', '2019-09-05 20:02:50'),
(180, 444, 'Hoře za nepoznané', 'Eva, jméno mé. Ze stromu utrhla jablko zkažené.\r\nPo utržení se z proslulého jablka stala kříšťálová koule.\r\n\r\nEvo, viz svět světů, vše nepoznané a nepoznatelné.\r\nStřih, růžová dečka\r\nVelké modré oči dívají se na svět.\r\n\r\nStřih, edenová zahrada\r\nPopínající keře, pugéty růží, na tisíckrát různý květ.\r\n\r\nStřih, kruh přátel\r\nNahá těla držící se v objetí, měkká něžnost společných let.\r\n\r\nStřih, nejkrásnější černé vlasy\r\nPatřící nejmilovanější osobě na světě, růžovému úsměvu, hlavě plné hvězd, očím dětské zvědavosti.\r\n\r\nTak Evo, řekla křišťálová koule,\r\nzhřešila si a to je zakázané.\r\n\r\nSvět světů, vše nepoznané a nepoznatelné. ', '2019-09-05 20:20:53'),
(181, 475, 'To co mělo zůstat zapomenuto', 'Měl jsem obvazy\r\nbyl jsem těžce raněn\r\nvložila jsi květy do vázy\r\ndotkla jsi se jemně mých ramen\r\n\r\nByl jsem slabý a blouznil jsem\r\npřál jsem si vidět tvojí tvář\r\npřeřízla jsi můj krk nožem\r\nbyl jsem tvůj naivní templář\r\n\r\nVěřím ti víc než sobě samému\r\nvěřím ti víc než svým smyslům\r\nkoneckonců smál bych se sobě starému\r\nradši nechám se zahrabat k cizím hrobům\r\n\r\nTvůj hlas u mého ucha zněl\r\na já se do pokoje uklidnil\r\nvyvarovat už tehdy jsem se tě měl\r\nto bych tvá přání neplnil\r\n\r\nTvé kdysi všední hnědé vlasy\r\ndíky nim je chvíle s tebou tolik krásná\r\nupřeš na mě své dlouhé řasy\r\nbylo to tolik zčista jasna\r\n\r\nNeslyšel jsem ani pořádně cos mi pošeptala\r\nteď už vezmu si to do hrobu\r\ncos mi řekla než ses odebrala\r\nna cestu k sobě do domu\r\n\r\nBolest přišla nečekaně\r\nstejně jako láska\r\nvztáhl jsem k tobě holé dlaně\r\njako na mých očích je páska\r\n\r\nJsem rád že skončilo to tvojí rukou\r\nnevím proč by to měla být nějaká jiná\r\nprotože byla to tvá ruka která zakryla mě dekou\r\na bylas to ty která za mnou poslala smrt jediná\r\n', '2019-09-05 22:59:43'),
(182, 441, 'Půlka', 'Ztratil jsem slova a cit k nim\r\nZtratil jsem sluch a možnost naslouchat hudbě jak nikdo jiný\r\nKde to všechno je? Kam se všechno vytratilo.\r\nProč už nejsou ty věci tak jak by měli být.\r\nChybí mi velká část mě a dokud nebude plná,\r\nbude to den co den, noc co noc, ton co ton a pocit co pocit stejné.\r\nStejné. Kde je ta  zábávná zvláštnost? \r\nTo divné? Díky, kterému se já cejtím jako já?\r\nNedokážu ani vyměnit slova, ikdyž vím že by mi to udělalo radost.', '2019-09-10 04:48:43'),
(183, 475, 'Spánek?', 'Zůstal jsem celou noc vzhůru abych tě slyšel dýchat\r\nnazahmouřil jsem oka, protože jesem nechtěl nevidět tvé vlasy\r\ni když jsem byl nemocnej nechtěl jsem kýchat\r\nnesnáším ve své hlavě všechny ty smutné hlasy\r\n\r\nProtože kdybych usnul a snil, už bych neviděl tenhle svůj sen\r\na pro tenhle sen jsem nejednou krvácel a plakal\r\njá totiž vím že až tahle noc skončí a bude zase den\r\nstudánku, kterou je tento sen zachvátí kal\r\n\r\nJá už nedokážu o tebe zase přijít až vyjde slunce\r\nproč hledat klid v lesích, když jím je každá minuta s tebou\r\nuž mě nebaví vstávat a s nadějí čekat jak dopadne mince\r\nco je to s náma a s celou touhle dobou\r\n\r\naž a pokud někdy zavřu oči abych neviděl tebe spící\r\nprotože i když se člověk může snažit jak může\r\na nikdy nebude toho momentu dost aby byl dost sytící\r\nnavždy mi to budou připomínat jizvy, které jsem si vyryl do kůže', '2019-09-29 10:50:22'),
(184, 444, 'Trojice', 'Zraňuje, zraňuje vědět,\r\nže někdo tě taky měl už někdy rád.\r\nStejně jako já.\r\nÚplně stejně.\r\nByl si pro ni vším.\r\nMilovali jste se veřejně, \r\nstejně jako my.\r\nŘekli jste si navždy?\r\nProtože i já ti to chci říct.\r\nNemám chuť ani jíst ani pít, žít?\r\nJestli se i nám zpřetrhá nit.\r\n\r\nJe to stejná hra?\r\nKdo si hraje na oběť,\r\na kdo na vraha?\r\n\r\nPíchá mě u srdce,\r\nkdyž třeba prochází se,\r\nokolo tebe tvá nová paní.\r\nTvá nová já. V mysli se ti prochází i ona.\r\nPředešlá já, já jako další ona.\r\n\r\nPoznáš někdy někoho jiného?', '2019-10-09 15:54:16'),
(185, 469, 'Snow', 'The sound of thoughts, they come and go,\r\nlike falling leaves before the snow\r\ncovers the land, or so to speak,\r\nit wipes the soul of all thats weak;\r\nthe doubts that sink us from the peak,\r\nand it might take  a week, a month or year\r\nagain to rise, to feel again, and realise that we mistake\r\nthe present for the past, and what comes last: the future\r\nleaves us paralysed,\r\nfor what we sow is what we fear\r\nthe most and what we reap for all we know is we are here and now,\r\nnot after.\r\n\r\nAnd yet,\r\nwe turn it all to laughter.', '2019-10-20 15:03:37'),
(186, 477, 'tábor', 'lidi nic neví\r\nale furt maj názor\r\nIQ zápor\r\nna mozku nádor\r\n\r\nuž nevim co s tim\r\nasi snad jen nábor\r\nvyvěsim fábor\r\nkoncentrační tábor', '2019-10-22 18:10:22'),
(187, 453, 'Noční můra', 'pod peřinou\r\ntěla se potí\r\nmezi stěnami\r\nse *** topí\r\n \r\nkrystaly bílé\r\nbarvy se točí \r\nna kočáru smrti \r\nsměje se kočí\r\n\r\ndesítky havranů\r\nchapadla chobotnice\r\npohlédl jsem do očí\r\ns dušemi obchodnice\r\n\r\nrarach tančící\r\nna lhářce\r\nměsíční svit\r\nv pokoji žár chce', '2019-10-23 07:24:57'),
(188, 469, 'slova', 'Trávím moc času ve vlastní hlavě\r\n\r\nV obavách z toho co najdu\r\n\r\nPřes okraj propasti je vidět jenom prázdnota\r\n\r\nDívat se na ní je horší než na sklenici plnou červů, kterou skrývá Pandořina skříňka\r\n\r\nNad propastí se klene všechno ostatní\r\n\r\nDaleko, ale jen vlásek od dosahu ruky\r\n\r\nSvět se otáčí a my s ním\r\n\r\nŽijeme, sníme, žijeme\r\n\r\nStavíme kolem sebe zdi z cihel\r\n\r\nÚl plný včel, které žijí a sní a otáčí se spolu se světem\r\n\r\nSvět se točí sám, nezáleží mu na tom s kým\r\n\r\nA ony se točí samy, kolem a dokola\r\n\r\nA klíče prší na chodník, hluk uším neunikne, padají z nebe a je snadné se v nich utopit\r\n\r\nJejich tok je jako zamlžené sklo na které děti píší prstem průpovídky\r\n\r\nRybář neví co dnes uloví, ale zítra bude jeho rodina mít znovu hlad\r\n\r\nA domů tápá v temonotě labyrintem z ostnatých drátů\r\n\r\nNa konci vždy projde dveřmi\r\n\r\nZa kterými nad sebou spatří dno propasti\r\n', '2019-10-23 20:20:03'),
(189, 450, 'Epitaf II', 'Kulka není to jediný co bych si měl nechat projít hlavou', '2019-10-23 20:33:39'),
(190, 475, 'Psáno bez důvodu', 'Šílenství, které tě drží jako tma světlo\r\na jeho krása, květin a stromům přináší ticho\r\nje to mé tělo ve kterém to ticho kvetlo\r\nvždy po noci plné dotyků zachvátí mě placho\r\n\r\nJenže moje, ale i tvoje paže\r\nkteré sahají na kvítek opadané růže\r\na nežli tyto divné okamžiky skončí\r\nbude kra plující Atlantikem o něco tenčí\r\n\r\nNehledáme odpuštění nebo další kávu\r\npromrhám radši všechnu tu potencionální slávu\r\ndošel jim v tom pajzlu čaj\r\nnebojte ale, ony vám ho ty hnědé oči daj\r\n\r\nnedopalky patří do popelníku nebo do koše\r\nco dělám ještě v lavici když to jde jednoduše\r\nViděl jsem co se jim stalo když odešli\r\nodpusť mi mé hříchy nevábný konšeli', '2019-10-28 20:51:47'),
(191, 453, 'How about another cigarette?', 'Do you smell that ash?\r\nWhen the sun is on horizon\r\nDo you smell that smoke?\r\nNever put your dress on\r\n\r\nCrystalizing tears on your face\r\nHow about another cigarette?\r\nI’ll be waiting to the filter\r\nSo stay with me longer\r\n\r\nHow about another cigarette?\r\nForget him my darling\r\nHow about another cigarette?\r\nI’ll help you forget him\r\n\r\nHow about another cigarette?\r\nLet’s open another wine\r\nTo kill some worst memories\r\nSo light another cigarette \r\n\r\nYou’ll never love me as him\r\nOur glass of love\r\nWon’t be filled to the grim\r\nSo exhale for while\r\n', '2019-10-28 21:01:12'),
(192, 444, 'Na pěst', 'Na pěst, tak ráda jsem na pěst.\r\nMiluju bolest.\r\nPodvědomě vyžaduju bolest.\r\nI od tebe\r\nNemůžu se propadnout do nebe.\r\nTam takový holky nemají rádi.\r\nJe mi ze sebe špatně, ale nemůžu se od toho oprostit.\r\nVyhledávám konflikt.\r\nNevím proč.\r\nBojím se.\r\nSvírám v kleště sebe i tebe.\r\nA všechny okolo.\r\nNezasloužím si nebe.\r\nNa pěst jako růže v odpadcích.\r\nMám duši v ostatcích.\r\nNevím jak se chovat.\r\nJak se neupřednostňovat.\r\nLhát, přetvařovat se, nebýt svá, klamat.\r\nJe jednodušší, než?\r\nZtrácím otěž.\r\nSebe samu.\r\nCelý můj život jde přes filtr.\r\nZkroucený, zašpiněný, politý kyselinou.\r\nNevím jak si to mám brát.\r\nNevím nic.\r\nPotřebuju tě štvát, kohokoliv.\r\nLíbí se mi, když mi dají lidi ochutnat ze své bolesti. \r\nKterou jsem jim způsobila já.\r\nNejsem důležitá.\r\nUbližuju jen sama sobě.\r\nNechápu, že se mnou máš ještě trpělivost.\r\nDochází dobrá vůle, písek se už téměř přesypal.\r\nZ mých slz zbyde jen krystal soli na tvářích.\r\nProč si tak ráda ubližuju?\r\nSama sebe ukřižuju. Jednoho dne.\r\nAž mi vše přestane procházet. \r\nNezasloužím si, abys mě měl rád.\r\nPýcha předchází pád.\r\nMúzu plodí jen bolest.', '2019-10-31 16:24:37'),
(193, 475, 'I.', 'Divokost je jen zapírání smutku\r\nsáhnout ti na ruku\r\njako sekaní do suku\r\ndostanu za to pořádně na budku\r\n\r\nKrása je jen zapírání světa\r\nprocházet se s tebou noční Prahou\r\nsmělost nazývat tě mou drahou\r\nza okny straší tvá silueta\r\n\r\nNaděje jen zapíráním zklamání\r\nopustila jsi mé kosti\r\nprý měla jsi toho dosti\r\nučinila jsi mi tisíceré kázání\r\n\r\nSmrt je zapírání života\r\nzněly housle, zněla violy\r\nkdyž oděn jsem byl v černé chocholy\r\nmilovala jsi prý kokota\r\n', '2019-11-19 15:53:46'),
(194, 479, 'Sobec', 'Slzy ti stékají po tvářích,\r\nmísí se mezi tvá poslední slova lásky\r\na jako padlí andělé vzhlížející marně k nebi,\r\nv křečích víří křídly labutími a hynou pod skleněnou klenbou\r\nočí tvých. \r\nVe víru planoucích listů\r\nstromy zakrývají jejich těla sněhobílá, \r\na sami se  věčně napřahují k nebi,\r\nkde andělská křídla kdysi snila.\r\n\r\n\r\nKolik andělů bych já zabil, kdyby aspoň jedna z těch slz patřila mi a záchvěv mých rtů vroucné lásky spatřila by...', '2019-11-25 16:07:03'),
(195, 475, 'Sny v realitě', 'Sny jsou od toho aby byly sněny \r\npokoj, které zdobí bílé stěny\r\npocit prázdnoty, který obchází opuštěný klášter\r\nna prach spálené srdce, které způsobilo ve mně kráter\r\n\r\nUnavenost životem a lejstra plná dávno mrtvých mužů\r\na já, plačící, přesvědčující se že ještě můžu\r\ns vůlí dál žít, ale bez vůle dál cítit\r\ns touhou pohladit její vlasy, a vědomím že srdce za to bude platit\r\n\r\nTěžké mraky, které povzbují mojí pokřivenou mysl\r\nkterá hledá ve změti ostnatých drátů života smysl\r\nmladý intelektuál, který si hází mincí, oprátku nebo pistoli\r\nje to tak trochu sebevražda, která nebolí', '2019-12-01 21:48:34'),
(196, 475, 'II.', 'Prostě to nemůžeš nechat jít\r\nsedíš na tom místě kdes jí políbil\r\nco bys dal dnes abys jí mohl dekou přikrýt\r\ndobře ale víš že to nejde ona si to už nedá líbit\r\n\r\nprosedělá matrace a proležené polštáře\r\nkaždý by něco chtěl\r\nChtěl bys jí zvednout roušku u oltáře?\r\nale ty jsi zaprášený posel\r\n\r\nChtěl bys to prostě nechat jíti\r\npotřebuješ si od ní odpočinout\r\nale stůl taky nejde odpolíti\r\nbez ní ale nedokážeš spočinout\r\n\r\nNeodvažuj se podívat za horizont\r\nleží tam a ty se bojíš zkrvavený obvaz odvinout\r\nnebe je bez hvězd a plné sond\r\nProč jsi jí nebyl schopný prominout?', '2019-12-01 22:41:34'),
(197, 479, 'ú - n - a - v - a', 'V ty noci, kdy mé mlčení \r\nčeří na hladině mé modré oči\r\na já, který se do tmy dívá,\r\nvidím černé kapky vína\r\nstékajících po skleněných tvářích\r\nlidské lhostejnosti.\r\n\r\nKam se poděli ty moje sny?\r\nKdy ve dne v noci\r\nbudeme věřit v nové cosi...\r\n\r\nAch to mé snění probdělé\r\nspřádá se v oční vaky,\r\nv uskupení slz malé,\r\nv otupění neznalé.\r\nTak hluboko ve vodě a topíme se myšlenkami.\r\n', '2019-12-02 18:43:29'),
(198, 479, ' ', 'Světlo line pomaleji,\r\nkdyž padá ti do dlaní.\r\n\r\nStařec tiše vzdychá zpod přikrývky.\r\nSnad se mu ještě zdají sny,\r\nkdy tiskne ruce mladé dívky.\r\nSlyšíš mě?\r\nNe, hladí ji po tváři,\r\nale jeho šedé vlasy odpočívají na polštáři.\r\n\r\nKoukám se z okna ven.\r\nHolubi víří křídly a tančí hrany parapetů.\r\nPoprvé vidím scénu okenního kabaretu.\r\n\r\nV těch prohlubních času \r\ns zmuchlanými lístky v kapse\r\nse zpocenými dlaněmi v klíně\r\na s prázdnotou v očích \r\nse dívám na své ruce.\r\nRuce které hází míčem, píší, hladí po vlasech,\r\nhrají si, když jsou nervózní, potí se, jsou bolavé,\r\nutírají slzy mé matce, tisknou ruce mého otce,\r\nhrají melodie, tleskají, jsou nesmělé,\r\nsnaží si udržet lásku a nikdy ji nepustit....\r\nChytit Tu holku a ….\r\nKoukat se jí do očí a....\r\nŘíct ji, že....\r\n\r\nVíčka se nám třepotají pod nánosem snů,\r\na já doufám, že to není konec našich dnů.\r\n', '2019-12-02 19:09:53'),
(199, 475, 'III.', 'Člověk, kterému došla vůle hledět na štěstí\r\nkterýmu nezbylo nic než pár lahví a trocha levného tabáku\r\nhledá v černých uličkách dávno zašlé poselství\r\nzatím co celý svět pro který žije ho má na háku.\r\n\r\nVšechno to zoufalství, které začalo opilým polibkem\r\nkteré jsem si vyplakal na rameni náhodnému starci\r\nnutí mě, naprosto zdravého člověka co si nerozumí se zbytkem\r\nk myšlenkám na oheň, který teď asi plane v jejím srdci\r\n\r\nOdjíždí ten kouř vycházející z okna taxíku\r\nmoje oči viděly, když mé ruce rozepínaly její šaty\r\nproklínám toho, kdo mi dal tuhle holku do vínku\r\ncopak je pád na beton lepší než do vaty?\r\n\r\nDětský zrak, který už nemám neviděl její chyby\r\nkteré si nalhávám každý večer než jdu sám ze sebe zvracet\r\nA ve snech ve kterých padám do tmy mě furt napadá co kdyby\r\nse ke mně, básníkovi, chtěla snad někdy vracet? ', '2019-12-04 18:21:14'),
(200, 475, 'Myšlenka nad přelétavou kráskou', 'Láska, milování, to vše bolí\r\nstejně jako když ránu zasypeš solí\r\nTy myšlenky si schováváme pro sebesamé\r\nněkteré věci budou na vždy dané\r\n\r\nS láskou tiskneme obrázky naší lásky\r\npoté co odnesla si naše srdce obepnuté pásky\r\nBudu si pamatovat jak líbala ́s mě\r\npotichu, osamotě, daleko ve tmě (jemně)\r\n\r\nKdyž ́s mi řekla poslední sbohem\r\nprocházeli jsme se podzimním polem\r\nTehdy to bylo jako na plátně stvořené\r\nDala ́s mi tehdy zpět mé srdce solené\r\n\r\nSeděl jsem pak v parku na lavičce\r\nutekla ́s mi tehdy jako pára pokličce\r\nMusela ́s být andělem s úsměvem\r\nabys mi ukázala co je mým údělem.', '2019-12-11 20:43:05'),
(201, 482, 'My Fucked Up Mind(1)', 'My dreams and hopes are shit. I know I am never achieving them, but there is still that part of me, that wants to fight, that wants to live a happy life, but I am too tired for everything, even sleeping.\r\nAs always, my life sucks. Can\'t do anything about it, just want to end it. It\'s not a pain as everyone else describes it. It\'s just &quot;emptiness&quot;. My psychologist says I am not empty, it\'s just a stupid feeling. Don\'t get me wrong, I do feel, except the good things. I get stressed out, I feel anxious, I feel unsatisfied and it\'s the same feeling over and over and over again. It\'s just boring, maybe that\'s the reason I am feeling empty.', '2019-12-13 22:39:50'),
(202, 483, 'Přemítaní před spaním ', 'Jsem jen básník ve velké mikině \r\nCo v hospodě u piva sedí \r\nCo s trochou strachu a nevinně \r\nNa obrovský svět hledí \r\n\r\nJen básník co romány psát neumí \r\nCo se rád potuluje v noci \r\nS přáním, ať své duši rozumí \r\nA emoce má ve své moci \r\n\r\nBásník co čeká na další den \r\nAž slunce přepere černou \r\nCo chce, ať se jeho sen \r\nVyplní, byť jen jednou \r\n\r\nJen básník co všechny své strasti \r\nRadši schová do hlavy \r\nProtože na životní pasti \r\nNemá dostatek odvahy \r\n\r\nA teď se ptám kým vlastně jsem?\r\nČlověk co se světa bojí? \r\nDítětem či básníkem?\r\nTipuju to na obojí \r\n\r\n', '2019-12-29 17:47:17'),
(203, 475, 'Madelaine', 'Ten polibek zpola zapomenutý\r\nmoje záda pro ní ohnutý\r\ndávno zapomenuý dotek mezi sny\r\nnad kterým přemýšlím už tři dny\r\n\r\nTen polibek zachumlaný v hnědých kadeřích\r\nosud stojící nevěřícně ve dveřích\r\npověz mi lásko, proč jsem blouznil po jiných\r\ndržíš mé srdce v dlaních\r\n\r\nZmožená pítím požádala´s mě ať na chvilku s tebou jsem\r\njá usedl uchvácen tím krásným nosem\r\ndlaň na dlani, ztrácím kontrolu vy mandlové oči\r\ndruhou rukou hladím tě po roztomilé tváři, hledí na nás smutný tvůj kočí\r\n\r\nvlhká připomínka nemoci z předloni\r\nco by na to řekli všichni oni\r\nMy vždycky budeme mít Paříž\r\nNa tebe a tvou krásu', '2020-01-01 20:19:22'),
(204, 483, 'Dlažební kostky', '\r\nHledám klid v ulicích Prahy \r\nKdyž už město šlo spát\r\nNevím, kde bere tolik snahy\r\nSi s mými city hrát \r\n\r\nMěsto mi klid nechce dát\r\nGryzavou zimou chce ublížit\r\nNaznačuje, že je čas jít spát\r\nNebo se k spřízněné duši přiblížit \r\n\r\nTěžko však ten úkol splnit\r\nSpát nejde a duše mi utekli\r\nRadši půjdu řádky plnit \r\nSlovy co mezi prsty protekly\r\n\r\nA ty mi slib, že v pořádku dorazíš\r\nMám pocitů spoustu, nechci ještě strach \r\nTřeba zlé duchy v mém městě porazíš\r\nA ráno je vítr odfoukne jak prach ', '2020-01-03 00:20:28');
INSERT INTO `posts` (`id`, `author`, `title`, `body`, `post_date`) VALUES
(205, 469, 'Umění zapomenout', 'Kde je ten čas\r\nkdy sem slyšel tvůj hlas\r\nPo stý se postim\r\nBoha se ptám kdy se od bolesti odprostim\r\nAle svět se točí život běží dál\r\nNa trůně sedí všech hoven král\r\nradši by se jenom smál \r\nTomu co bylo dřív\r\na jestli to má vliv\r\nna to co přijde\r\npotom co slunce zase vyjde\r\nspoza clony okamžiku\r\nV oka mžiku\r\nkapky ležej na chodníku\r\nztrácej se ve víku od kanálu\r\nVibrace vesmírnýho signálu\r\nkterej uvidíš až když pochopíš že spíš\r\na že blíž seš spíš když umíš třetí oko neotvírat\r\nDokázat neskomírat a vnímat nejenom se dívat\r\na do kroku ostatních píseň zpívat\r\ns cizíma osobnostma splívat\r\na spílat si že neumíš bejt sám sebou \r\nkdyž nejsi s tou se kterou se ti myšlenky v hlavě dohromady melou\r\na za obojek tě berou\r\nNa místo kde můžeš v klidu vydechnout\r\nnadechnout se a ohlídnout se před sebe\r\nPřes strop se dívat na nebe\r\n\r\nA z tebe už mi taky celkem jebe.', '2020-01-04 22:47:50'),
(206, 484, 'Poslouchám', 'Stojím na vysokém útesu\r\nPátrám po oceánských vlnách\r\nJarní vánek bere mi vlasy z účesu\r\nLechtivým dotekem mi hladí tvář\r\n\r\nSlyším jen šumění vody\r\nSlyším jen vlny narážející o skálu\r\n\r\nLehám si do vlhké stráně\r\nMé tělo našlo v sobě klidu\r\nZkoumám své dětské dlaně\r\nMyslíš, že mohu v klidu spát?\r\n\r\nSlyším jen  šustění trávy\r\nSlyším, neslyším, spím\r\n', '2020-01-06 20:57:04'),
(218, 1, 'Tyvole ouje', 'ouje tyvole\n\n\nto je vono bejby', '2020-01-07 21:56:34');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `username` varchar(150) NOT NULL,
  `email` varchar(250) NOT NULL,
  `password` varchar(600) NOT NULL,
  `regdate` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `username`, `email`, `password`, `regdate`) VALUES
(1, 'test', 'test@test.com', 'test', '2019-12-14 00:46:29');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`),
  ADD KEY `author` (`author`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(6) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=219;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
